source 'https://rubygems.org'


gem 'rails', '4.2.1'

gem 'rails-api'

gem 'spring', :group => :development
gem "httparty"
gem 'pg'
gem 'devise', '3.4.1'
gem 'rack-cors', :require => 'rack/cors'

gem 'thin'
gem 'bcrypt', '~> 3.1.0'

gem 'responders'


group :development, :test do 
  gem 'byebug'
  gem 'pry-rails'
  gem 'pry-byebug'
  gem 'rspec-rails', '~> 3.0'
  gem 'capybara'
end
